/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/beta/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Beta */
        get: operations["getBeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog Route */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/{ticker}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Coverage Route */
        get: operations["getCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporate-actions/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Corporate Actions */
        get: operations["getCorporateActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Correlation */
        get: operations["getCorrelation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/distribution/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Distribution */
        get: operations["getDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ohlcv/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ohlcv */
        get: operations["getOhlcv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance */
        get: operations["getPerformance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Route
         * @description Best-effort LOCAL fetch into the cache via quant_core (never used in CI; yfinance is best-effort).
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/returns/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Returns */
        get: operations["getReturns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rolling/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rolling */
        get: operations["getRolling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionMarker */
        ActionMarker: {
            /** Kind */
            kind: string;
            /** T */
            t: number;
            /** Value */
            value: number;
        };
        /** BetaResponse */
        BetaResponse: {
            /** Alpha */
            alpha: number | null;
            /** Benchmark */
            benchmark: string;
            /** Beta */
            beta: number | null;
            meta: components["schemas"]["SeriesMeta"];
            /** N */
            n: number;
            /** R Squared */
            r_squared: number | null;
            /** Rolling */
            rolling?: components["schemas"]["Point"][] | null;
            /** Ticker */
            ticker: string;
        };
        /** CatalogResponse */
        CatalogResponse: {
            /** Count */
            count: number;
            /** Empty */
            empty: boolean;
            /** Hint */
            hint?: string | null;
            /** Items */
            items: components["schemas"]["DatasetMetaOut"][];
            /** Universe */
            universe: string[];
        };
        /** CorporateActionsResponse */
        CorporateActionsResponse: {
            /** Adj Factor */
            adj_factor: components["schemas"]["Point"][];
            /** Dividends */
            dividends: components["schemas"]["ActionMarker"][];
            meta: components["schemas"]["SeriesMeta"];
            /** Splits */
            splits: components["schemas"]["ActionMarker"][];
            /** Ticker */
            ticker: string;
        };
        /** CorrelationResponse */
        CorrelationResponse: {
            /** Clustered */
            clustered: boolean;
            /** Matrix */
            matrix: (number | null)[][];
            meta: components["schemas"]["SeriesMeta"];
            /** Method */
            method: string;
            /** Tickers */
            tickers: string[];
        };
        /** CoverageOut */
        CoverageOut: {
            /** End */
            end: string | null;
            /** Interval */
            interval: string;
            /** Last Session Gap */
            last_session_gap: number;
            /** Missing Pct */
            missing_pct: number;
            /** N Expected */
            n_expected: number;
            /** N Present */
            n_present: number;
            /** Start */
            start: string | null;
            /** Ticker */
            ticker: string;
        };
        /** DatasetMetaOut */
        DatasetMetaOut: {
            /** End */
            end: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /** Interval */
            interval: string | null;
            /** Modified At */
            modified_at: string;
            /** N Bytes */
            n_bytes: number;
            /** N Rows */
            n_rows: number;
            /** Provider */
            provider?: string | null;
            /** Source */
            source: string;
            /** Start */
            start: string | null;
            /** Tickers */
            tickers: string[];
        };
        /** DistributionResponse */
        DistributionResponse: {
            /** Drawdown */
            drawdown: components["schemas"]["Point"][];
            histogram: components["schemas"]["HistogramOut"];
            /** Kind */
            kind: string;
            meta: components["schemas"]["SeriesMeta"];
            moments: components["schemas"]["MomentsOut"];
            normal?: components["schemas"]["NormalOut"] | null;
            qq?: components["schemas"]["QQOut"] | null;
            /** Ticker */
            ticker: string;
        };
        /**
         * Field
         * @enum {string}
         */
        Field: "open" | "high" | "low" | "close" | "adj_close" | "volume";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramOut */
        HistogramOut: {
            /** Bin Centers */
            bin_centers: number[];
            /** Bin Edges */
            bin_edges: number[];
            /** Counts */
            counts: number[];
            /** Density */
            density: boolean;
        };
        /** MetaOut */
        MetaOut: {
            /**
             * Api
             * @default v1
             */
            api: string;
            /** Quant Core Version */
            quant_core_version: string;
            /**
             * Sources
             * @default []
             */
            sources: string[];
            /** Version */
            version: string;
        };
        /** MomentsOut */
        MomentsOut: {
            /** Kurtosis Excess */
            kurtosis_excess: number | null;
            /** Mean */
            mean: number | null;
            /** N */
            n: number;
            /** Skew */
            skew: number | null;
            /** Std */
            std: number | null;
        };
        /** NamedSeries */
        NamedSeries: {
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["Point"][];
        };
        /** NormalOut */
        NormalOut: {
            /** Jb Pvalue */
            jb_pvalue: number;
            /** Jb Stat */
            jb_stat: number;
            /** Mu */
            mu: number;
            /** Sigma */
            sigma: number;
        };
        /** OHLCVBar */
        OHLCVBar: {
            /** Adj */
            adj: number | null;
            /** C */
            c: number | null;
            /** H */
            h: number | null;
            /** Low */
            low: number | null;
            /** O */
            o: number | null;
            /** T */
            t: number;
            /** V */
            v: number | null;
        };
        /** OHLCVResponse */
        OHLCVResponse: {
            /** Bars */
            bars: components["schemas"]["OHLCVBar"][];
            /** Interval */
            interval: string;
            meta: components["schemas"]["SeriesMeta"];
            /** Ticker */
            ticker: string;
        };
        /** PerformanceResponse */
        PerformanceResponse: {
            /** Base */
            base: number;
            meta: components["schemas"]["SeriesMeta"];
            /** Series */
            series: components["schemas"]["NamedSeries"][];
            /** Tickers */
            tickers: string[];
        };
        /** Point */
        Point: {
            /** T */
            t: number;
            /** V */
            v: number | null;
        };
        /** QQOut */
        QQOut: {
            /** Intercept */
            intercept: number;
            /** Sample */
            sample: number[];
            /** Slope */
            slope: number;
            /** Theoretical */
            theoretical: number[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Tickers */
            tickers?: string[] | null;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
            /** Rows */
            rows: number;
            /** Tickers */
            tickers: string[];
        };
        /**
         * ReturnKind
         * @enum {string}
         */
        ReturnKind: "simple" | "log";
        /** ReturnsResponse */
        ReturnsResponse: {
            /** Kind */
            kind: string;
            meta: components["schemas"]["SeriesMeta"];
            /** Series */
            series: components["schemas"]["Point"][];
            /** Ticker */
            ticker: string;
        };
        /** RollingResponse */
        RollingResponse: {
            /** Annualized */
            annualized: boolean;
            meta: components["schemas"]["SeriesMeta"];
            /** Series */
            series: components["schemas"]["Point"][];
            /** Stat */
            stat: string;
            /** Ticker */
            ticker: string;
            /** Window */
            window: number;
        };
        /**
         * RollingStat
         * @enum {string}
         */
        RollingStat: "vol" | "mean" | "sharpe";
        /**
         * SeriesMeta
         * @description Honest provenance/shape: where it came from, how big, whether it was downsampled.
         */
        SeriesMeta: {
            /**
             * Downsampled
             * @default false
             */
            downsampled: boolean;
            /**
             * Empty
             * @default false
             */
            empty: boolean;
            /** End */
            end?: string | null;
            /**
             * N Raw
             * @default 0
             */
            n_raw: number;
            /**
             * N Returned
             * @default 0
             */
            n_returned: number;
            /** Source */
            source?: string | null;
            /** Start */
            start?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBeta: {
        parameters: {
            query?: {
                benchmark?: string;
                start?: string | null;
                end?: string | null;
                window?: number | null;
                kind?: components["schemas"]["ReturnKind"];
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCoverage: {
        parameters: {
            query?: {
                interval?: string;
                calendar?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCorporateActions: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                interval?: string;
                source?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporateActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCorrelation: {
        parameters: {
            query: {
                /** @description comma-separated tickers */
                tickers: string;
                start?: string | null;
                end?: string | null;
                kind?: components["schemas"]["ReturnKind"];
                field?: components["schemas"]["Field"];
                method?: string;
                cluster?: boolean;
                interval?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDistribution: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                kind?: components["schemas"]["ReturnKind"];
                field?: components["schemas"]["Field"];
                bins?: string;
                qq?: boolean;
                normality?: boolean;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    getOhlcv: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                interval?: string;
                source?: string | null;
                max_points?: number | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OHLCVResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPerformance: {
        parameters: {
            query: {
                /** @description comma-separated tickers */
                tickers: string;
                start?: string | null;
                end?: string | null;
                field?: components["schemas"]["Field"];
                base?: number;
                interval?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getReturns: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                kind?: components["schemas"]["ReturnKind"];
                field?: components["schemas"]["Field"];
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRolling: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                window?: number;
                stat?: components["schemas"]["RollingStat"];
                annualize?: boolean;
                rf?: number;
                kind?: components["schemas"]["ReturnKind"];
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
